"""
Django settings for p2 project.
Attempt to bring pathagar up to Django v1.10

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Note: double use of os.path.dirname so end up with project
# directory.  As of Jan 21 2017 returns "/Pj/p2". (Project/pathagar2)
# Relationship to pathagar's CUR_DIR????

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*qt0nr_z)-e1$vto^fg%0p+5irp@i1ftzapzdka@t-zlok^-pd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # Not in pathagar.


# Application definition

INSTALLED_APPS = [
    # already in pathagar:
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    # brought in from pathagar:
    'books',
    # in pathagar but not yet brought in:
#   'django.contrib.sites',
#   'django.contrib.comments',
#   'tagging', # TODO old
#   'taggit',
    # here by default but not in pathagar:
    'django.contrib.messages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # new
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # new
]

ROOT_URLCONF = 'p2.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
# The following (deprecated)
#TEMPLATE_DIRS = (
#    os.path.join(os.path.dirname(__file__), 'templates'),
#)  replaced by:
        'DIRS': [
            os.path.join(os.path.dirname(__file__), 'templates'),],
#       'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
# TEMPLATE_DEBUG = DEBUG replaced by next line:
            'debug':  DEBUG,
# TEMPLATE_LOADERS = (
#   'django.template.loaders.filesystem.Loader',
#   'django.template.loaders.app_directories.Loader',
# )  is replaced by :   (see 
# https://docs.djangoproject.com/en/1.10/ref/templates/upgrading/
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',

                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'p2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True  # NOT in pathagar

USE_TZ = True  # NOT in pathagar


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

### Pathagar specific constants (brought in from pathagar) ###

# Books settings:

BOOKS_PER_PAGE = 20 # Number of books shown per page in the OPDS
                    # catalogs and in the HTML pages.

BOOKS_STATICS_VIA_DJANGO = True
DEFAULT_BOOK_STATUS = 'Published'

# Allow non logued users to upload books
ALLOW_PUBLIC_ADD_BOOKS = False

# sendfile settings:

SENDFILE_BACKEND = 'sendfile.backends.development'

# Get current directory to get media and templates while developing:
CUR_DIR = u'' + os.path.dirname(__file__)
# Currently returns "u'p2'".

ADMINS = (
    # ('Your Name', 'your_email@domain.com'),
)

MANAGERS = ADMINS

SITE_ID = 1

MEDIA_ROOT = os.path.join(CUR_DIR, 'static_media')

MEDIA_URL = '/static_media/'

deprecatedMIDDLEWARE_CLASSES = """
MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware', # ok
    'django.contrib.sessions.middleware.SessionMiddleware', # ok
    'django.middleware.csrf.CsrfViewMiddleware', # ok
    'django.contrib.auth.middleware.AuthenticationMiddleware', # ok
    'django.contrib.messages.middleware.MessageMiddleware', # ok
)                             """

INTERNAL_IPS = ('127.0.0.1',)

STATIC_ROOT = os.path.join(CUR_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(CUR_DIR, 'static'),
)

ALLOW_USER_COMMENTS = False

if __name__ == "__main__":
    print("CUR_DIR is {}".format(CUR_DIR))
    print("BASE_DIR is {}".format(BASE_DIR))
    print("os.path.dirname(__file__) returns {}"
                    .format(os.path.dirname(__file__)))
    print("os.path.abspath(__file__) returns {}"
                    .format(os.path.abspath(__file__)))

